<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CI workflows" tests="1" skipped="0" failures="1" errors="0" timestamp="2025-09-12T14:43:10.394Z" hostname="AURAKAI" time="0.007">
  <properties/>
  <testcase name="workflow YAML exists when README references GitHub Actions workflows()" classname="docs.MarkdownFileValidationTest$DocumentationLinks$ContinuousIntegration" time="0.007">
    <failure message="org.opentest4j.AssertionFailedError: README references GitHub Actions workflows but no standard workflow YAML found: [.github/workflows/build.yml, .github/workflows/build.yaml, .github/workflows/ci.yml, .github/workflows/ci.yaml] ==&gt; expected: &lt;true&gt; but was: &lt;false&gt;" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: README references GitHub Actions workflows but no standard workflow YAML found: [.github/workflows/build.yml, .github/workflows/build.yaml, .github/workflows/ci.yml, .github/workflows/ci.yaml] ==&gt; expected: &lt;true&gt; but was: &lt;false&gt;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at docs.MarkdownFileValidationTest$DocumentationLinks$ContinuousIntegration.workflow YAML exists when README references GitHub Actions workflows(MarkdownFileValidationTest.kt:572)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
